In [1]:
import matplotlib.pyplot as plt
import numpy as np
from scipy.optimize import curve_fit
import pandas as pd

In [2]:
table = pd.read_excel("width_calib.xls")

In [15]:
data.shape

(3792, 121)

In [15]:
table

edge  realx  realy  real_scale    real_w  extracted_w  \
0   2040;1749   1.23   0.00        1.88  6.542553         52.0   
1   2040;2378   1.08   0.59        1.84  6.688316         56.0   
2   2040;1953   1.07   0.19        1.84  5.906186         46.0   
3   1991;2237   0.34   1.22        1.84  6.883104         63.0   
4   2497;2329   0.24   1.47        1.84  8.094908         62.0   
5   2497;2459   0.97   0.43        1.84  5.766507         56.0   
6   3765;4017   0.34   1.71        1.84  9.475400         61.0   
7   3187;3179   0.93   0.29        1.96  4.970236         30.6   
8   3116;3187   0.32   1.35        1.96  7.078610         51.0   
9   3187;3325   0.61   1.59        1.96  8.688762         53.0   
10  2852;2972   0.55   1.59        1.90  8.854941         51.0   
11    940;890   0.68   0.46        1.90  4.320921         44.0   
12    940;831   1.16   0.93        1.90  7.825132         65.0   
13   940;1005   1.02   0.74        1.90  6.632414         51.0   
14    775;811   1.25   0.99        1.96  8.135476         68.0   
15    775;786   0.62   0.85        1.90  5.537332         42.5   
16    775;633   1.12   0.76        1.90  7.123758         71.0   
17    454;492   1.53   0.54        1.83  8.866110         62.0   
18    454;481   0.70   0.95        1.83  6.448319         39.0   
19    454;410   0.59   1.39        1.83  8.251547         67.0   
20    396;378   1.41   0.00        1.87  7.540107         56.0   
21    396;438   0.45   1.47        1.87  8.221045         42.0   
22    831;940   1.03   0.81        1.85  7.082938         65.0   
23    831;920   0.38   0.93        1.85  5.430482         57.0   
24    831;811   1.03   0.81        1.85  7.082938         63.0   
25  1239;1213   0.84   1.04        1.87  7.148995         58.0   
26  1239;1054   0.48   0.82        1.87  5.081058         53.0   
27  1239;1331   0.76   1.21        1.87  7.641073         65.0   
28  2145;2025   0.57   1.12        1.80  6.981678         54.0   
29  2145;2131   0.64   0.57        1.80  4.761276         36.0   
30  2131;2183   0.44   0.96        1.80  5.866835         45.0   
31  2468;2164   0.96   1.38        1.80  9.339284         52.0   
32  2468;2634   0.77   1.54        1.80  9.565402         50.0   
33  2468;2205   0.73   0.72        1.80  5.696273         42.0   
34  2901;3041   0.71   1.11        1.88  7.008774         54.0   
35  2901;2903   1.03   0.00        1.88  5.478723         50.0   
36  2901;2734   0.43   1.17        1.88  6.630400         49.0   
37  3396;3375   0.89   0.91        1.82  6.993795         49.0   
38  3396;3625   1.08   1.08        1.82  8.392037         60.0   
39  3805;3658   1.18   0.95        1.82  8.323586         58.0   
40  3805;3893   0.96   1.15        1.82  8.230945         55.0   
41  3805;3767   0.41   0.61        1.82  4.038368         49.0   
42  3893;3805   1.07   1.43        1.82  9.813193         55.0   
43  3893;3992   1.18   1.34        1.82  9.810424         60.0   
44  3893;3897   1.04   0.52        1.82  6.388766         34.0   
45  4116;4095   1.44   0.19        1.82  7.980663         56.0   
46  4018;3923   1.20   0.85        1.82  8.079913         57.0   
47  3758;3812   0.49   1.06        1.82  6.416350         43.0   
48  3758;3683   1.17   0.00        1.82  6.428571         36.0   
49  3758;3747   0.82   0.54        1.82  5.394698         39.0   
50  3593;3620   0.96   0.00        1.82  5.274725         35.7   
51  3593;3229   0.29   1.03        1.82  5.879378         42.0   
52  3593;3544   0.70   0.18        1.82  3.971277         29.0   

    Extracted_other  Extracted_gaussian  
0         16.165781           47.573749  
1         17.855333           51.382735  
2         13.672368           36.288240  
3         22.090684           54.975664  
4         21.876426           58.588916  
5         18.461902           48.734690  
6         16.352954           48.025684  
7         11.850233                 NaN  
8         13.120323                 NaN  
9         14.607233     

In [3]:
edges = [(int(edge.split(";")[0]), int(edge.split(";")[1])) for edge in table["edge"]]

In [4]:
widths_real = [float(width) for width in table["real_w"]]

In [5]:
%matplotlib widget

import os
import sys

sys.path.insert(0, os.getenv("HOME") + "/pycode/MscThesis/")
import pandas as pd
from amftrack.util.sys import (
    get_dates_datetime,
    get_dirname,
    temp_path,
    get_plate_number,
    get_postion_number,
)

import ast
from amftrack.plotutil import plot_t_tp1
from scipy import sparse
from datetime import datetime
from amftrack.pipeline.functions.node_id import orient
import pickle
import scipy.io as sio
from pymatreader import read_mat
from matplotlib import colors
import cv2
import imageio
import matplotlib.pyplot as plt
import numpy as np
from skimage.filters import frangi
from skimage import filters
from random import choice
import scipy.sparse
import os
from amftrack.pipeline.functions.extract_graph import (
    from_sparse_to_graph,
    generate_nx_graph,
    sparse_to_doc,
)
from skimage.feature import hessian_matrix_det
from amftrack.pipeline.functions.experiment_class_surf import Experiment, Edge, Node
from amftrack.pipeline.paths.directory import (
    run_parallel,
    find_state,
    directory_scratch,
    directory_project,
)
from amftrack.notebooks.analysis.util import *
from scipy import stats
from scipy.ndimage.filters import uniform_filter1d
from statsmodels.stats import weightstats as stests
from skimage.measure import profile_line
from amftrack.notebooks.analysis.util import *


def get_source_image(experiment, pos, t, local, force_selection=None):
    x, y = pos[0], pos[1]
    ims, posimg = experiment.find_image_pos(x, y, t, local)
    if force_selection is None:
        dist_border = [
            min([posimg[1][i], 3000 - posimg[1][i], posimg[0][i], 4096 - posimg[0][i]])
            for i in range(posimg[0].shape[0])
        ]
        j = np.argmax(dist_border)
    else:
        dist_last = [
            np.linalg.norm(
                np.array((posimg[1][i], posimg[0][i])) - np.array(force_selection)
            )
            for i in range(posimg[0].shape[0])
        ]
        j = np.argmin(dist_last)
    return (ims[j], (posimg[1][j], posimg[0][j]))


def get_profile_pixel(
    edge,
    index,
    im,
    pivot,
    before,
    after,
    t,
    size=20,
    width_factor=60,
    averaging_size=100,
    threshold_averaging=10,
):
    imtab = im
    #     print(imtab.shape)
    #     print(int(max(0,pivot[0]-averaging_size)),int(pivot[0]+averaging_size))
    threshold = np.mean(
        imtab[
            int(max(0, pivot[0] - averaging_size)) : int(pivot[0] + averaging_size),
            int(max(0, pivot[1] - averaging_size)) : int(pivot[1] + averaging_size),
        ]
        - threshold_averaging
    )
    orientation = np.array(before) - np.array(after)
    perpendicular = (
        [1, -orientation[0] / orientation[1]] if orientation[1] != 0 else [0, 1]
    )
    perpendicular_norm = np.array(perpendicular) / np.sqrt(
        perpendicular[0] ** 2 + perpendicular[1] ** 2
    )
    point1 = np.around(np.array(pivot) + width_factor * perpendicular_norm)
    point2 = np.around(np.array(pivot) - width_factor * perpendicular_norm)
    point1 = point1.astype(int)
    point2 = point2.astype(int)
    p = profile_line(imtab, point1, point2, mode="constant")
    return p


def get_profile_edge(edge, resolution, t, local=False, threshold_averaging=10):
    pixel_conversion_factor = 1.725
    pixel_list = edge.pixel_list(t)
    pixels = []
    indexes = []
    source_images = []
    poss = []
    profiles = []
    if len(pixel_list) > 3 * resolution:
        for i in range(0, len(pixel_list) // resolution):
            index = i * resolution
            indexes.append(index)
            pixel = pixel_list[index]
            pixels.append(pixel)
            source_img, pos = get_source_image(edge.experiment, pixel, t, local)
            source_images.append(source_img)
            poss.append(pos)
    else:
        indexes = [0, len(pixel_list) // 2, len(pixel_list) - 1]
        for index in indexes:
            pixel = pixel_list[index]
            pixels.append(pixel)
            source_img, pos = get_source_image(edge.experiment, pixel, t, local)
            source_images.append(source_img)
            poss.append(pos)
    #     print(indexes)
    for i, index in enumerate(indexes[1:-1]):
        source_img = source_images[i + 1]
        pivot = poss[i + 1]
        _, before = get_source_image(edge.experiment, pixels[i], t, local, pivot)
        _, after = get_source_image(edge.experiment, pixels[i + 2], t, local, pivot)
        #         plot_t_tp1([0,1,2],[],{0 : pivot,1 : before, 2 : after},None,source_img,source_img)
        profile = get_profile_pixel(
            edge,
            index,
            source_img,
            pivot,
            before,
            after,
            t,
            threshold_averaging=threshold_averaging,
        )
        #         print(width*pixel_conversion_factor)
        profiles.append(profile[:120])
    #         if i>=1:
    #             break
    return profiles

In [6]:
from scipy import special


def func2(x, lapse, lapse2, c, d, e):
    return (
        -c * (special.erf(e * (x - lapse)) - special.erf(e * (x - lapse - lapse2))) + d
    )


def func3(x, lapse, lapse2, c, d, e, lapse4):
    return (
        -c * (special.erf(e * (x - lapse)) - special.erf(e * (x - (lapse + lapse2))))
        + d
        + c
        * (
            special.erf(e * (x - (lapse + lapse2)))
            - special.erf(e * (x - (lapse + lapse2 + lapse4)))
        )
    )


def func4(x, lapse, lapse2, c, d, e, lapse4):
    return (
        -c * (special.erf(e * (x - lapse)) - special.erf(e * (x - (lapse + lapse2))))
        + d
        + c * (special.erf(e * (x - (lapse - lapse4))) - special.erf(e * (x - (lapse))))
    )

In [7]:
from skimage.measure import profile_line
from amftrack.notebooks.analysis.util import *


def get_source_image(experiment, pos, t, local, force_selection=None):
    x, y = pos[0], pos[1]
    ims, posimg = experiment.find_image_pos(x, y, t, local)
    if force_selection is None:
        dist_border = [
            min([posimg[1][i], 3000 - posimg[1][i], posimg[0][i], 4096 - posimg[0][i]])
            for i in range(posimg[0].shape[0])
        ]
        j = np.argmax(dist_border)
    else:
        dist_last = [
            np.linalg.norm(
                np.array((posimg[1][i], posimg[0][i])) - np.array(force_selection)
            )
            for i in range(posimg[0].shape[0])
        ]
        j = np.argmin(dist_last)
    return (ims[j], (posimg[1][j], posimg[0][j]))


def get_width_pixel(
    edge,
    index,
    im,
    pivot,
    before,
    after,
    t,
    size=20,
    width_factor=60,
    averaging_size=100,
    threshold_averaging=10,
):
    imtab = im
    #     print(imtab.shape)
    #     print(int(max(0,pivot[0]-averaging_size)),int(pivot[0]+averaging_size))
    threshold = np.mean(
        imtab[
            int(max(0, pivot[0] - averaging_size)) : int(pivot[0] + averaging_size),
            int(max(0, pivot[1] - averaging_size)) : int(pivot[1] + averaging_size),
        ]
        - threshold_averaging
    )
    orientation = np.array(before) - np.array(after)
    perpendicular = (
        [1, -orientation[0] / orientation[1]] if orientation[1] != 0 else [0, 1]
    )
    perpendicular_norm = np.array(perpendicular) / np.sqrt(
        perpendicular[0] ** 2 + perpendicular[1] ** 2
    )
    point1 = np.around(np.array(pivot) + width_factor * perpendicular_norm)
    point2 = np.around(np.array(pivot) - width_factor * perpendicular_norm)
    point1 = point1.astype(int)
    point2 = point2.astype(int)
    p = profile_line(imtab, point1, point2, mode="constant")
    xdata = np.array(range(len(p)))
    ydata = np.array(p)
    #     fig = plt.figure()
    #     ax = fig.add_subplot(111)
    #     ax.plot(xdata,ydata)
    #     p0a=[60,10,100,180,0.1]
    #     popt1, pcov = curve_fit(func2, xdata, ydata,bounds = ([0,0,0,0,0],[120,120,200]+2*[np.inf]),p0=p0a)
    p0b = [60, 10, 100, 180, 0.1] + [10]
    popt2, pcov = curve_fit(
        func3,
        xdata,
        ydata,
        bounds=([0, 0, 0, 0, 0, 0], [120, 120, 200] + 2 * [np.inf] + [120]),
        p0=p0b,
    )
    residuals = ydata - func3(xdata, *popt2)
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((ydata - np.mean(ydata)) ** 2)
    r_squared1 = 1 - (ss_res / ss_tot)
    popt3, pcov = curve_fit(
        func4,
        xdata,
        ydata,
        bounds=([0, 0, 0, 0, 0, 0], [120, 120, 200] + 2 * [np.inf] + [120]),
        p0=p0b,
    )
    residuals = ydata - func4(xdata, *popt3)
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((ydata - np.mean(ydata)) ** 2)
    r_squared2 = 1 - (ss_res / ss_tot)
    #     ax.plot(xdata, func2(xdata, *popt1), 'r-')
    if r_squared1 > r_squared2:
        #         ax.plot(xdata, func3(xdata, *popt2), 'b-')
        popt = popt2
    else:
        #         ax.plot(xdata, func4(xdata, *popt3), 'b-')
        popt = popt3
    return popt


def get_width_edge(edge, resolution, t, local=False, threshold_averaging=10):
    pixel_conversion_factor = 1.725
    pixel_list = edge.pixel_list(t)
    pixels = []
    indexes = []
    source_images = []
    poss = []
    profiles = []
    if len(pixel_list) > 3 * resolution:
        for i in range(0, len(pixel_list) // resolution):
            index = i * resolution
            indexes.append(index)
            pixel = pixel_list[index]
            pixels.append(pixel)
            source_img, pos = get_source_image(edge.experiment, pixel, t, local)
            source_images.append(source_img)
            poss.append(pos)
    else:
        indexes = [0, len(pixel_list) // 2, len(pixel_list) - 1]
        for index in indexes:
            pixel = pixel_list[index]
            pixels.append(pixel)
            source_img, pos = get_source_image(edge.experiment, pixel, t, local)
            source_images.append(source_img)
            poss.append(pos)
    #     print(indexes)
    for i, index in enumerate(indexes[1:-1]):
        source_img = source_images[i + 1]
        pivot = poss[i + 1]
        _, before = get_source_image(edge.experiment, pixels[i], t, local, pivot)
        _, after = get_source_image(edge.experiment, pixels[i + 2], t, local, pivot)
        #         plot_t_tp1([0,1,2],[],{0 : pivot,1 : before, 2 : after},None,source_img,source_img)
        popt = get_width_pixel(
            edge,
            index,
            source_img,
            pivot,
            before,
            after,
            t,
            threshold_averaging=threshold_averaging,
        )
        profiles.append(popt)
    return profiles

In [8]:
directory = "/projects/0/einf914/data/"
exp = get_exp((10, 104, 104), directory)
exp.load_compressed_skel()

begin = 2020-12-17 08:39:00 
  end = 2020-12-17 08:39:00


In [9]:
plt.close("all")
node1 = 940
node2 = 831
profiles = get_width_edge(Edge(Node(node1, exp), Node(node2, exp), exp), 50, 0)
profiles

[array([3.77214974e+01, 3.66585379e+01, 1.76767573e+01, 1.03640405e+02,
        9.57066067e-02, 2.45987819e+01]),
 array([3.88773127e+01, 3.75097642e+01, 1.86840147e+01, 1.05580770e+02,
        9.75916848e-02, 2.25294051e+01]),
 array([3.59626959e+01, 3.77122854e+01, 1.84406620e+01, 1.06901692e+02,
        1.03824221e-01, 2.38819665e+01]),
 array([3.76831134e+01, 3.73898652e+01, 1.86782488e+01, 1.07355566e+02,
        9.58332569e-02, 2.44109514e+01]),
 array([3.72317675e+01, 3.85434884e+01, 1.79689369e+01, 1.09218173e+02,
        9.50222353e-02, 2.23405132e+01]),
 array([3.70588769e+01, 3.67999701e+01, 1.82867364e+01, 1.10452754e+02,
        1.02209560e-01, 2.39012842e+01]),
 array([3.69330898e+01, 3.92386294e+01, 1.85949548e+01, 1.12498642e+02,
        9.99394287e-02, 2.24654942e+01]),
 array([4.19583337e+01, 4.07165519e+01, 2.02695835e+01, 1.14611751e+02,
        9.68045894e-02, 2.00874335e+01]),
 array([4.29821987e+01, 3.92615802e+01, 1.90813323e+01, 1.13469328e+02,
        9.414855

In [63]:
reg.predict(profiles[0].reshape(1, -1))

array([7.13585728])

In [123]:
np.random.choice(8, 10)

array([4, 3, 1, 4, 4, 5, 5, 4, 6, 7])

In [9]:
data = []

for i, edge in enumerate(edges):
    print(i)
    if edge != (2852, 2972):
        node1 = edge[0]
        node2 = edge[1]
        profiles = get_width_edge(Edge(Node(node1, exp), Node(node2, exp), exp), 10, 0)
        all_profiles = []
        for profile in profiles:
            prof_list = list(profile)
            all_profiles.append(prof_list)
        indexes = np.random.choice(len(all_profiles), 20)
        for index in indexes:
            data.append(all_profiles[index] + [widths_real[i]])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


RuntimeError: Optimal parameters not found: The maximum number of function evaluations is exceeded.

In [10]:
data = np.array(data, dtype=np.float)

In [75]:
shape = len(data[0]), len(data)
array = np.zeros(shape, dtype=float)
for i, line in enumerate(data):
    print(len(line))
    array[:, i] = line

121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121
121


In [11]:
data[:, :6], data[:, 6]

(array([[4.92446200e+01, 2.90159813e+01, 2.95533820e+01, 1.60416427e+02,
         8.85984404e-02, 1.16778631e+01],
        [4.63129006e+01, 7.50910734e+00, 1.99999369e+02, 1.55457603e+02,
         5.83531329e-02, 6.81326300e+00],
        [4.97493874e+01, 2.92123362e+01, 3.06689709e+01, 1.59993796e+02,
         9.52352874e-02, 1.10630146e+01],
        ...,
        [7.17900369e+01, 7.33338687e+00, 6.32390105e+01, 9.70424873e+01,
         5.45560274e-02, 1.31829953e+01],
        [7.17900369e+01, 7.33338687e+00, 6.32390105e+01, 9.70424873e+01,
         5.45560274e-02, 1.31829953e+01],
        [3.63226943e+01, 3.95286808e+01, 1.72703283e+01, 1.20242914e+02,
         9.59214321e-02, 7.96037367e+00]]),
 array([6.54255319, 6.54255319, 6.54255319, 6.54255319, 6.54255319,
        6.54255319, 6.54255319, 6.54255319, 6.54255319, 6.54255319,
        6.54255319, 6.54255319, 6.54255319, 6.54255319, 6.54255319,
        6.54255319, 6.54255319, 6.54255319, 6.54255319, 6.54255319,
        6.68831649, 6.6

In [12]:
fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(data[:, 1], data[:, 6])

/home/cbisot/anaconda3/envs/test/lib/python3.7/site-packages/matplotlib/__init__.py:880: MatplotlibDeprecationWarning: 
nbagg.transparent
  version, key, obj_type="rcparam", alternative=alt_key)


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [13]:
from sklearn.linear_model import LinearRegression

X1 = data[:, 1].reshape(-1, 1)
X2 = data[:, 1:6]
y = data[:, 6]
reg2 = LinearRegression().fit(X1, y)
reg = LinearRegression().fit(X2, y)

In [ ]:
reg.score(X2, y), reg2.score(X1, y)

In [24]:
reg.coef_, reg.intercept_

(array([ 1.37542907e-02, -3.60485453e-03,  8.29994347e-03, -7.50403382e+00,
        -1.63506586e-02]),
 6.740512691422062)

In [148]:
reg2.coef_, reg2.intercept_

(array([0.03361492]), 6.101188804913019)

In [40]:
data.shape

(1786, 7)

In [77]:
data[:, 1]

array([72.06905201, 13.91247771, 25.14766165, ...,  8.33870952,
        7.33338687, 50.53865139])

In [78]:
reg2.predict(data[:, 1].reshape(-1, 1))

array([7.88250102, 7.13282667, 7.27765516, ..., 7.06097733, 7.0480181 ,
       7.60496079])

In [136]:
fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(reg2.predict(data[:, 1].reshape(-1, 1)), data[:, 6])

/home/cbisot/anaconda3/envs/test/lib/python3.7/site-packages/matplotlib/__init__.py:880: MatplotlibDeprecationWarning: 
nbagg.transparent
  version, key, obj_type="rcparam", alternative=alt_key)


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [14]:
fig = plt.figure()
ax = fig.add_subplot(111)
for i in range(data.shape[0]):
    ax.scatter(reg.predict([data[i, 1:6]]), data[i, 6])
    reg.predict([data[i, 1:6]]), data[i, 6]

/home/cbisot/anaconda3/envs/test/lib/python3.7/site-packages/matplotlib/__init__.py:880: MatplotlibDeprecationWarning: 
nbagg.transparent
  version, key, obj_type="rcparam", alternative=alt_key)


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [15]:
from skimage.measure import profile_line
from amftrack.notebooks.analysis.util import *


def get_source_image(experiment, pos, t, local, force_selection=None):
    x, y = pos[0], pos[1]
    ims, posimg = experiment.find_image_pos(x, y, t, local)
    if force_selection is None:
        dist_border = [
            min([posimg[1][i], 3000 - posimg[1][i], posimg[0][i], 4096 - posimg[0][i]])
            for i in range(posimg[0].shape[0])
        ]
        j = np.argmax(dist_border)
    else:
        dist_last = [
            np.linalg.norm(
                np.array((posimg[1][i], posimg[0][i])) - np.array(force_selection)
            )
            for i in range(posimg[0].shape[0])
        ]
        j = np.argmin(dist_last)
    return (ims[j], (posimg[1][j], posimg[0][j]))


def get_width_pixel(
    edge,
    index,
    im,
    pivot,
    before,
    after,
    t,
    size=20,
    width_factor=60,
    averaging_size=100,
    threshold_averaging=10,
):
    imtab = im
    #     print(imtab.shape)
    #     print(int(max(0,pivot[0]-averaging_size)),int(pivot[0]+averaging_size))
    threshold = np.mean(
        imtab[
            int(max(0, pivot[0] - averaging_size)) : int(pivot[0] + averaging_size),
            int(max(0, pivot[1] - averaging_size)) : int(pivot[1] + averaging_size),
        ]
        - threshold_averaging
    )
    orientation = np.array(before) - np.array(after)
    perpendicular = (
        [1, -orientation[0] / orientation[1]] if orientation[1] != 0 else [0, 1]
    )
    perpendicular_norm = np.array(perpendicular) / np.sqrt(
        perpendicular[0] ** 2 + perpendicular[1] ** 2
    )
    point1 = np.around(np.array(pivot) + width_factor * perpendicular_norm)
    point2 = np.around(np.array(pivot) - width_factor * perpendicular_norm)
    point1 = point1.astype(int)
    point2 = point2.astype(int)
    p = profile_line(imtab, point1, point2, mode="constant")
    xdata = np.array(range(len(p)))
    ydata = np.array(p)
    #     fig = plt.figure()
    #     ax = fig.add_subplot(111)
    #     ax.plot(xdata,ydata)
    #     p0a=[60,10,100,180,0.1]
    #     popt1, pcov = curve_fit(func2, xdata, ydata,bounds = ([0,0,0,0,0],[120,120,200]+2*[np.inf]),p0=p0a)
    p0b = [60, 10, 100, 180, 0.1] + [10]
    popt2, pcov = curve_fit(
        func3,
        xdata,
        ydata,
        bounds=([0, 0, 0, 0, 0, 0], [120, 120, 200] + 2 * [np.inf] + [120]),
        p0=p0b,
    )
    residuals = ydata - func3(xdata, *popt2)
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((ydata - np.mean(ydata)) ** 2)
    r_squared1 = 1 - (ss_res / ss_tot)
    popt3, pcov = curve_fit(
        func4,
        xdata,
        ydata,
        bounds=([0, 0, 0, 0, 0, 0], [120, 120, 200] + 2 * [np.inf] + [120]),
        p0=p0b,
    )
    residuals = ydata - func4(xdata, *popt3)
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((ydata - np.mean(ydata)) ** 2)
    r_squared2 = 1 - (ss_res / ss_tot)
    #     ax.plot(xdata, func2(xdata, *popt1), 'r-')
    if r_squared1 > r_squared2:
        #         ax.plot(xdata, func3(xdata, *popt2), 'b-')
        popt = popt2
    else:
        #         ax.plot(xdata, func4(xdata, *popt3), 'b-')
        popt = popt3
    ret = np.array(popt[1:])
    return reg.predict(ret.reshape(1, -1))


def get_width_edge(edge, resolution, t, local=False, threshold_averaging=10):
    pixel_conversion_factor = 1.725
    pixel_list = edge.pixel_list(t)
    pixels = []
    indexes = []
    source_images = []
    poss = []
    widths = []
    if len(pixel_list) > 3 * resolution:
        for i in range(0, len(pixel_list) // resolution):
            index = i * resolution
            indexes.append(index)
            pixel = pixel_list[index]
            pixels.append(pixel)
            source_img, pos = get_source_image(edge.experiment, pixel, t, local)
            source_images.append(source_img)
            poss.append(pos)
    else:
        indexes = [0, len(pixel_list) // 2, len(pixel_list) - 1]
        for index in indexes:
            pixel = pixel_list[index]
            pixels.append(pixel)
            source_img, pos = get_source_image(edge.experiment, pixel, t, local)
            source_images.append(source_img)
            poss.append(pos)
    #     print(indexes)
    for i, index in enumerate(indexes[1:-1]):
        source_img = source_images[i + 1]
        pivot = poss[i + 1]
        _, before = get_source_image(edge.experiment, pixels[i], t, local, pivot)
        _, after = get_source_image(edge.experiment, pixels[i + 2], t, local, pivot)
        #         plot_t_tp1([0,1,2],[],{0 : pivot,1 : before, 2 : after},None,source_img,source_img)
        width = get_width_pixel(
            edge,
            index,
            source_img,
            pivot,
            before,
            after,
            t,
            threshold_averaging=threshold_averaging,
        )
        widths.append(width)
    return widths

In [16]:
widths_real_select = []
widths_calculated = []
for i, edge in enumerate(edges):
    if edge != (2852, 2972):
        node1 = edge[0]
        node2 = edge[1]
        widths = get_width_edge(Edge(Node(node1, exp), Node(node2, exp), exp), 50, 0)
        widths_real_select.append(widths_real[i])
        widths_calculated.append(np.mean(list(widths)))

In [26]:
fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(widths_calculated, widths_real_select)
ax.plot(
    np.linspace(4, 10, 100), reg3.coef_[0] * np.linspace(4, 10, 100) + reg3.intercept_
)
ax.set_xlim(4, 10)
ax.set_ylim(4, 10)
ax.set_xlabel("width_calculated(um)")
ax.set_ylabel("width_real(um)")

/home/cbisot/anaconda3/envs/test/lib/python3.7/site-packages/matplotlib/__init__.py:880: MatplotlibDeprecationWarning: 
nbagg.transparent
  version, key, obj_type="rcparam", alternative=alt_key)


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0, 0.5, 'width_real(um)')

In [19]:
X3 = np.array(widths_calculated, dtype=np.float).reshape(-1, 1)
y = widths_real_select
reg3 = LinearRegression().fit(X3, y)

In [32]:
def func(x, a, b):
    return a * x + b


popt1, pcov = curve_fit(func, X3, np.array(y))

ValueError: object too deep for desired array

error: Result from function call is not a proper array of floats.

In [ ]:
popt

In [24]:
X3 = np.array(widths_calculated[:17] + widths_calculated[18:], dtype=np.float).reshape(
    -1, 1
)
y = widths_real_select[:17] + widths_real_select[18:]
reg3 = LinearRegression().fit(X3, y)

In [25]:
reg3.coef_, reg3.intercept_

(array([2.36506932]), -9.964681546814028)

In [23]:
np.argmin(widths_calculated)

17

In [20]:
np.save("dataset_fit", np.array(data, dtype=np.float))

In [21]:
data = np.load("dataset_fit.npy")
np.random.shuffle(data)
data

array([[5.74214915e+00, 1.08271031e-01, 1.71317402e+02, ...,
        2.01658378e+01, 5.42389386e+01, 5.86683501e+00],
       [9.08025666e+00, 7.47059729e-02, 1.70959807e+02, ...,
        2.53704346e+01, 4.60188845e+01, 6.98167796e+00],
       [8.06013078e+00, 7.25544659e-02, 1.50524221e+02, ...,
        1.76197598e+01, 5.75954720e+01, 9.56540190e+00],
       ...,
       [6.39457499e+00, 5.77043439e-02, 1.74253002e+02, ...,
        1.07664298e+01, 5.05945359e+01, 9.33928382e+00],
       [8.53878741e+00, 4.69651165e-02, 1.43728905e+02, ...,
        9.57109536e+00, 6.51536813e+01, 4.03836809e+00],
       [1.71934250e+01, 8.57831015e-02, 1.42682337e+02, ...,
        3.42545221e+01, 4.00502001e+01, 7.64107316e+00]])

In [22]:
pd.DataFrame(data).to_csv("dataset_fit.csv")

In [76]:
np.load("d")

array([[161.        , 158.        , 159.        , ..., 162.        ,
        164.        ,   6.54255319],
       [161.        , 158.        , 159.        , ..., 162.        ,
        164.        ,   6.54255319],
       [161.        , 164.        , 164.        , ..., 129.        ,
        126.        ,   6.54255319],
       ...,
       [162.        , 166.        , 162.        , ..., 159.        ,
        155.        ,   6.54255319],
       [161.        , 162.        , 160.        , ..., 159.        ,
        157.        ,   6.54255319],
       [161.        , 162.        , 160.        , ..., 159.        ,
        157.        ,   6.54255319]])

In [53]:
np.array(data, dtype=np.float)

ValueError: setting an array element with a sequence.

In [52]:
[np.array(line, dtype=np.float) for line in data]

[array([154.        , 158.        , 161.        , 158.        ,
        159.        , 162.        , 161.        , 158.        ,
        159.        , 162.        , 161.        , 163.        ,
        164.        , 163.        , 164.        , 164.        ,
        164.        , 165.        , 164.        , 163.        ,
        164.        , 164.        , 164.        , 164.        ,
        165.        , 166.        , 166.        , 165.        ,
        164.        , 162.        , 162.        , 163.        ,
        161.        , 158.        , 158.        , 158.        ,
        152.        , 151.        , 150.        , 147.        ,
        147.        , 142.        , 139.        , 136.        ,
        132.        , 130.        , 130.        , 126.        ,
        122.        , 123.        , 120.        , 121.        ,
        116.        , 118.        , 115.        , 115.        ,
        114.        , 112.        , 112.        , 113.        ,
        112.        , 116.        , 114.