# Renaming the files with bas name

Renames the generated BAS folder to add the BAS name to them.

## Setup

In [44]:
import numpy as np
from numpy import array
import os

In [45]:
path = "/data/felix/BAS/86_20220622"

In [46]:
sub_dir = os.listdir(path)
print(sub_dir[:5])

['bas-x19500.0-y39500.0-size1500', 'bas-x15300.0-y45020.0-size1500', 'bas-x21425.0-y32900.0-size1500', 'bas-x6850.0-y28650.0-size1500', 'bas-x14390.0-y33220.0-size1500']


In [47]:
bas_coord = [
    array([16400, 44780]),
    array([15300, 45020]),
    array([14000, 44450]),
    array([14300, 44000]),
    array([13100, 44160]),
    array([12800, 43840]),
    array([12210, 42670]),
    array([12480, 43000]),
    array([12680, 42490]),
    array([12020, 41940]),
    array([12120, 41690]),
    array([12770, 41380]),
    array([13380, 41210]),
    array([10560, 41770]),
    array([10760, 41080]),
    array([10000, 41330]),
    array([10340, 41300]),
    array([11530, 39840]),
    array([9170, 41300]),
    array([9600, 40980]),
    array([4240, 38000]),
    array([3830, 37020]),
    array([5650, 35290]),
    array([1690, 32900]),
    array([1200, 32080]),
    array([3470, 26650]),
    array([280, 28220]),
    array([1580, 25560]),
    array([3820, 24310]),
    array([4400, 24220]),
    array([4710, 24430]),
    array([5420, 24030]),
    array([9710, 13920]),
    array([10200, 12870]),
    array([6610, 12250]),
    array([6720, 13320]),
    array([5420, 14750]),
    array([5040, 17530]),
    array([7300, 19550]),
    array([14330, 25450]),
    array([13940, 26450]),
    array([13640, 26350]),
    array([13170, 28500]),
    array([14390, 33220]),
    array([15170, 35100]),
    array([15720, 34160]),
    array([16230, 35710]),
    array([16640, 35230]),
    array([17760, 37820]),
    array([18270, 39450]),
    array([18070, 40950]),
    array([7460, 31210]),
    array([7050, 31220]),
    array([7280, 30790]),
    array([17350, 19700]),
    array([11140, 20230]),
    array([16000, 16970]),
    array([12080, 19950]),
    array([12040, 19770]),
    array([12730, 19770]),
    array([6790, 28610]),
    array([9880, 37110]),
]

bas_coord = [c.astype(float) for c in bas_coord]

In [48]:
len(bas_coord)

62

## Test

In [50]:
count = 0
for c in bas_coord:
    name = f"bas-x{c[0]}-y{c[1]}-size1500"
    print(name in sub_dir)
    if name in sub_dir:
        l = os.listdir(os.path.join(path, name))
        number_files = len(l)
        print(number_files)
        count += 1
print(f"Final result: {count}")

True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
True
163
False
False
Final result: 60


## Modify names

In [54]:
for i, c in enumerate(bas_coord):
    name = f"bas-x{c[0]}-y{c[1]}-size1500"
    print(name in sub_dir)
    if name in sub_dir:
        new_name = f"{i+1}_bas-x{c[0]}-y{c[1]}-size1500"
        os.rename(os.path.join(path, name), os.path.join(path, new_name))
        # print(os.path.join(path, new_name))

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
False


In [19]:
for c in bas_coord:
    name = f"bas-x{c[0]}-y{c[1]}-size1500"
    if name in sub_dir:
        # os.rename(src, dst)
        print(os.path.join(path, name))

/data/felix/BAS/86_20220622/bas-x16400.0-y44780.0-size1500
/data/felix/BAS/86_20220622/bas-x15300.0-y45020.0-size1500
/data/felix/BAS/86_20220622/bas-x14000.0-y44450.0-size1500
/data/felix/BAS/86_20220622/bas-x14300.0-y44000.0-size1500
/data/felix/BAS/86_20220622/bas-x13100.0-y44160.0-size1500
/data/felix/BAS/86_20220622/bas-x12800.0-y43840.0-size1500
/data/felix/BAS/86_20220622/bas-x12210.0-y42670.0-size1500
/data/felix/BAS/86_20220622/bas-x12480.0-y43000.0-size1500
/data/felix/BAS/86_20220622/bas-x12120.0-y41690.0-size1500
/data/felix/BAS/86_20220622/bas-x12770.0-y41380.0-size1500
/data/felix/BAS/86_20220622/bas-x13380.0-y41210.0-size1500
/data/felix/BAS/86_20220622/bas-x10760.0-y41080.0-size1500
/data/felix/BAS/86_20220622/bas-x10000.0-y41330.0-size1500
/data/felix/BAS/86_20220622/bas-x10340.0-y41300.0-size1500
/data/felix/BAS/86_20220622/bas-x9170.0-y41300.0-size1500
/data/felix/BAS/86_20220622/bas-x9600.0-y40980.0-size1500
/data/felix/BAS/86_20220622/bas-x4240.0-y38000.0-size1500
